import {
  BusinessResponse,
  CategoryResponse,
  ReviewResponse,
  ServiceResponse,
} from '../models/bipsy.models';

/**
 * Datos de maqueta. **Solo se usan en desarrollo y solo si el backend no
 * responde** (ver `BipsyService.orDemo`). Sirven para poder trabajar el
 * diseño sin levantar la API; nunca para tapar un error.
 */

export const DEMO_CATEGORIES: CategoryResponse[] = [
  { id: 2, code: 'BARBER', name: 'Barbería', active: true },
  { id: 3, code: 'HAIRDRESSER', name: 'Peluquería', active: true },
  { id: 4, code: 'ESTHETIC', name: 'Estética', active: true },
  { id: 5, code: 'NAILS', name: 'Uñas', active: true },
  { id: 6, code: 'MASSAGE', name: 'Masajes', active: true },
  { id: 7, code: 'MAKEUP', name: 'Maquillaje', active: true },
  { id: 8, code: 'COACHING', name: 'Coaching', active: true },
  { id: 9, code: 'PHOTOGRAPHY', name: 'Fotografía', active: true },
  { id: 10, code: 'TUTORING', name: 'Clases particulares', active: true },
  { id: 11, code: 'OTHER', name: 'Otros', active: true },
];

export const DEMO_BUSINESSES: BusinessResponse[] = [
  {
    id: 1,
    name: 'Barbería El Maestro',
    city: 'Osuna',
    province: 'Sevilla',
    address: 'Plaza Mayor 3',
    phone: '954 987 654',
    description: 'Barbería tradicional andaluza. Corte clásico, afeitado a navaja y arreglo de barba con mimo y profesionalidad.',
    profileImageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1400&q=80',
    autonomous: true,
    averageRating: 5.0,
    reviewCount: 2,
    categories: [{ id: 2, code: 'BARBER', name: 'Barbería', primary: true }],
  },
  {
    id: 2,
    name: 'Peluquería & Estética Luna',
    city: 'Sevilla',
    province: 'Sevilla',
    address: 'Calle Sierpes 14',
    phone: '954 123 789',
    description: 'Especialistas en estilismo moderno, mechas balayage y tratamiento capilar intensivo con productos premium.',
    profileImageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1400&q=80',
    autonomous: false,
    averageRating: 4.9,
    reviewCount: 18,
    categories: [{ id: 3, code: 'HAIRDRESSER', name: 'Peluquería', primary: true }],
  },
  {
    id: 3,
    name: 'Studio Barber Co.',
    city: 'Morón de la Frontera',
    province: 'Sevilla',
    address: 'Av. de Andalucía 8',
    phone: '954 555 999',
    description: 'Ambiente urbano con degradados impecables, perfilado con toalla caliente y tratamiento facial.',
    profileImageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=800&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=1400&q=80',
    autonomous: true,
    averageRating: 4.8,
    reviewCount: 12,
    categories: [{ id: 2, code: 'BARBER', name: 'Barbería', primary: true }],
  },
  {
    id: 4,
    name: 'Nails & Beauty Chic',
    city: 'Osuna',
    province: 'Sevilla',
    address: 'Calle Sevilla 45',
    phone: '954 888 222',
    description: 'Manicura semipermanente, esculpido de uñas en gel y diseño personalizado para cada clienta.',
    profileImageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=1400&q=80',
    autonomous: true,
    averageRating: 5.0,
    reviewCount: 8,
    categories: [{ id: 5, code: 'NAILS', name: 'Uñas', primary: true }],
  },
  {
    id: 5,
    name: 'Spa Relax Center',
    city: 'Sevilla',
    province: 'Sevilla',
    address: 'Alameda de Hércules 22',
    phone: '954 321 000',
    description: 'Centro de bienestar con masajes terapéuticos, tratamientos faciales y terapia de aromas.',
    profileImageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1400&q=80',
    autonomous: false,
    averageRating: 4.7,
    reviewCount: 34,
    categories: [{ id: 6, code: 'MASSAGE', name: 'Masajes', primary: true }],
  },
  {
    id: 6,
    name: 'Korta Barbershop',
    city: 'Écija',
    province: 'Sevilla',
    address: 'Calle Real 7',
    phone: '954 765 432',
    description: 'Barbería moderna con ambiente premium. Fade degradado, diseño de barba y productos exclusivos.',
    profileImageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=1400&q=80',
    autonomous: true,
    averageRating: 4.9,
    reviewCount: 21,
    categories: [{ id: 2, code: 'BARBER', name: 'Barbería', primary: true }],
  },
];

export const DEMO_SERVICES = (businessId: number): ServiceResponse[] => [
  {
    id: 101,
    businessId,
    name: 'Corte clásico',
    description: 'Corte a máquina y tijera con acabado impecable',
    duration: 30,
    price: 15,
    active: true,
  },
  {
    id: 102,
    businessId,
    name: 'Afeitado tradicional',
    description: 'Afeitado a navaja con toalla caliente y bálsamo',
    duration: 45,
    price: 20,
    active: true,
  },
  {
    id: 103,
    businessId,
    name: 'Corte + perfilado de barba',
    description: 'Corte completo con perfilado y arreglo de barba',
    duration: 45,
    price: 25,
    active: true,
  },
];

export const DEMO_REVIEWS: ReviewResponse[] = [
  {
    id: 1,
    businessId: 1,
    authorName: 'Sofía Ruiz',
    rating: 5,
    serviceName: 'Afeitado tradicional',
    comment: 'El afeitado a navaja es una experiencia. Recomendable al 100 %.',
  },
  {
    id: 2,
    businessId: 1,
    authorName: 'Miguel Torres',
    rating: 5,
    serviceName: 'Corte clásico',
    comment: 'Servicio excepcional y muy puntual. Volveré sin duda.',
  },
];
